"""upgrade_logger_to_audit_table

Revision ID: 3627d9edccfe
Revises: a8c8bbf7fb04
Create Date: 2025-11-19 11:56:06.920663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3627d9edccfe'
down_revision: Union[str, Sequence[str], None] = 'a8c8bbf7fb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loggers', sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'))
    op.add_column('loggers', sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'))
    op.add_column('loggers', sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP方法'))
    op.add_column('loggers', sa.Column('request_path', sa.String(length=255), nullable=True, comment='请求路径'))
    op.add_column('loggers', sa.Column('request_id', sa.String(length=32), nullable=True, comment='请求ID'))
    op.add_column('loggers', sa.Column('session_id', sa.String(length=32), nullable=True, comment='会话ID'))
    op.add_column('loggers', sa.Column('audit_level', sa.String(length=20), nullable=True, comment='审计级别'))
    op.add_column('loggers', sa.Column('operation_type', sa.String(length=50), nullable=True, comment='操作类型'))
    op.add_column('loggers', sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'))
    op.add_column('loggers', sa.Column('resource_id', sa.String(length=32), nullable=True, comment='资源ID'))
    op.add_column('loggers', sa.Column('operation_result', sa.String(length=20), nullable=True, comment='操作结果'))
    op.add_column('loggers', sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险级别'))
    op.add_column('loggers', sa.Column('before_data', sa.Text(), nullable=True, comment='操作前数据'))
    op.add_column('loggers', sa.Column('after_data', sa.Text(), nullable=True, comment='操作后数据'))
    op.add_column('loggers', sa.Column('sensitive_flag', sa.Boolean(), nullable=True, comment='敏感操作标记'))
    op.add_column('loggers', sa.Column('compliance_flag', sa.Boolean(), nullable=True, comment='合规标记'))
    op.add_column('loggers', sa.Column('business_context', sa.Text(), nullable=True, comment='业务上下文'))
    
    # 添加审计索引
    op.create_index('idx_audit_userid_created', 'loggers', ['userid', 'created_at'])
    op.create_index('idx_audit_action_result', 'loggers', ['action', 'operation_result'])
    op.create_index('idx_audit_risk_level', 'loggers', ['risk_level', 'created_at'])
    op.create_index('idx_audit_resource', 'loggers', ['resource_type', 'resource_id'])
    op.create_index('idx_audit_session', 'loggers', ['session_id', 'created_at'])
    op.create_index('idx_audit_request_id', 'loggers', ['request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除索引
    op.drop_index('idx_audit_request_id', 'loggers')
    op.drop_index('idx_audit_session', 'loggers')
    op.drop_index('idx_audit_resource', 'loggers')
    op.drop_index('idx_audit_risk_level', 'loggers')
    op.drop_index('idx_audit_action_result', 'loggers')
    op.drop_index('idx_audit_userid_created', 'loggers')
    
    # 删除字段
    op.drop_column('loggers', 'business_context')
    op.drop_column('loggers', 'compliance_flag')
    op.drop_column('loggers', 'sensitive_flag')
    op.drop_column('loggers', 'after_data')
    op.drop_column('loggers', 'before_data')
    op.drop_column('loggers', 'risk_level')
    op.drop_column('loggers', 'operation_result')
    op.drop_column('loggers', 'resource_id')
    op.drop_column('loggers', 'resource_type')
    op.drop_column('loggers', 'operation_type')
    op.drop_column('loggers', 'audit_level')
    op.drop_column('loggers', 'session_id')
    op.drop_column('loggers', 'request_id')
    op.drop_column('loggers', 'request_path')
    op.drop_column('loggers', 'request_method')
    op.drop_column('loggers', 'user_agent')
    op.drop_column('loggers', 'ip_address')
    # ### end Alembic commands ###
