"""fix_resource_table_constraint_quotes

Revision ID: 424afa6b7566
Revises: e77169ba4a78
Create Date: 2025-11-20 09:43:09.498763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424afa6b7566'
down_revision: Union[str, Sequence[str], None] = 'e77169ba4a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建正确的约束（使用单引号和大写枚举值）
    op.create_check_constraint(
        'check_menu_menutype_required',
        'resources',
        "rtype != 'MENU' OR menu_type IS NOT NULL"
    )
    op.create_check_constraint(
        'check_button_parent_required',
        'resources',
        "rtype != 'BUTTON' OR parent_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除约束
    op.drop_constraint('check_menu_menutype_required', 'resources', type_='check')
    op.drop_constraint('check_button_parent_required', 'resources', type_='check')
    # ### end Alembic commands ###
