"""add column category

Revision ID: 4a9c5e5b47c2
Revises: 0434f25633f3
Create Date: 2025-10-20 09:30:40.826064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9c5e5b47c2'
down_revision: Union[str, Sequence[str], None] = '0434f25633f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileassets', sa.Column('category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fileassets', 'category')
    # ### end Alembic commands ###
