"""完善表结构

Revision ID: 4f055d31e49f
Revises: update_enums_nullable
Create Date: 2025-11-14 15:25:12.319153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f055d31e49f'
down_revision: Union[str, Sequence[str], None] = 'update_enums_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_area_grants', 'rid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.add_column('user_role_scopes', sa.Column('status', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('user_role_scopes', sa.Column('is_default', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role_scopes', 'is_default')
    op.drop_column('user_role_scopes', 'status')
    op.alter_column('role_area_grants', 'rid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
