"""add_geo_location_to_audit_logs

Revision ID: 58733a662944
Revises: ebcee47f145b
Create Date: 2025-11-19 13:57:35.095185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58733a662944'
down_revision: Union[str, Sequence[str], None] = 'ebcee47f145b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('country', sa.String(length=100), nullable=True, comment='国家'))
    op.add_column('audit_logs', sa.Column('region', sa.String(length=100), nullable=True, comment='地区/省份'))
    op.add_column('audit_logs', sa.Column('city', sa.String(length=100), nullable=True, comment='城市'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'city')
    op.drop_column('audit_logs', 'region')
    op.drop_column('audit_logs', 'country')
    # ### end Alembic commands ###
