"""完善资源表约束

Revision ID: 5e03359a8dd5
Revises: c7c771d1290d
Create Date: 2025-11-13 15:29:20.429392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e03359a8dd5'
down_revision: Union[str, Sequence[str], None] = 'c7c771d1290d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
