"""Rename transacion_id to transaction_id in transactions table

Revision ID: 6999cdf385c8
Revises: 
Create Date: 2025-09-29 17:40:01.388323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6999cdf385c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 先添加一个可空的新列
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=32), nullable=True))
        batch_op.alter_column('remark',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # 将旧列的值复制到新列
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE transactions SET transaction_id = transacion_id"))

    # 设置新列为NOT NULL并创建索引，然后删除旧列
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.drop_index(batch_op.f('ix_transactions_transacion_id'))
        batch_op.drop_column('transacion_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transacion_id', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.create_index(batch_op.f('ix_transactions_transacion_id'), ['transacion_id'], unique=1)
        batch_op.alter_column('remark',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
