"""fix_audit_logs_nullable_fields

Revision ID: 7909db436dc0
Revises: b7275bb96197
Create Date: 2025-11-19 12:23:23.786809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7909db436dc0'
down_revision: Union[str, Sequence[str], None] = 'b7275bb96197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_comment='操作用户ID')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_comment='客户端IP地址')
    op.alter_column('audit_logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_comment='HTTP请求方法')
    op.alter_column('audit_logs', 'request_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='请求路径')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'request_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='请求路径')
    op.alter_column('audit_logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_comment='HTTP请求方法')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_comment='客户端IP地址')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_comment='操作用户ID')
    # ### end Alembic commands ###
