"""init on postgres

Revision ID: 8d563ec9b845
Revises: 
Create Date: 2025-11-20 17:21:22.214584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d563ec9b845'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('area_id', sa.String(length=32), nullable=False),
    sa.Column('area_code', sa.String(length=20), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_index(op.f('ix_areas_area_code'), 'areas', ['area_code'], unique=True)
    op.create_index(op.f('ix_areas_area_id'), 'areas', ['area_id'], unique=True)
    op.create_index(op.f('ix_areas_parent_code'), 'areas', ['parent_code'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=32), nullable=False, comment='审计唯一标识'),
    sa.Column('user_id', sa.String(length=32), nullable=True, comment='操作用户ID'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='操作用户名'),
    sa.Column('session_id', sa.String(length=32), nullable=True, comment='会话ID'),
    sa.Column('role_id', sa.String(length=32), nullable=True, comment='角色ID'),
    sa.Column('request_id', sa.String(length=32), nullable=True, comment='请求ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='客户端IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP请求方法'),
    sa.Column('request_path', sa.String(length=255), nullable=True, comment='请求路径'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP响应状态码'),
    sa.Column('response_time', sa.Float(), nullable=True, comment='响应时间(秒)'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国家'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='地区/省份'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='城市'),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True, comment='设备指纹'),
    sa.Column('browser_type', sa.String(length=50), nullable=True, comment='浏览器类型'),
    sa.Column('os_type', sa.String(length=50), nullable=True, comment='操作系统类型'),
    sa.Column('operation_type', sa.String(length=20), nullable=False, comment='操作类型(CREATE/UPDATE/DELETE/READ/LOGIN/LOGOUT)'),
    sa.Column('operation_module', sa.String(length=50), nullable=False, comment='操作模块'),
    sa.Column('operation_description', sa.String(length=200), nullable=False, comment='操作描述'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型(USER/TRANSACTION/ROLE/SYSTEM)'),
    sa.Column('resource_id', sa.String(length=32), nullable=True, comment='资源ID'),
    sa.Column('resource_name', sa.String(length=200), nullable=True, comment='资源名称'),
    sa.Column('audit_level', sa.String(length=20), nullable=False, comment='审计级别(INFO/WARNING/ERROR/CRITICAL)'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='风险级别(LOW/MEDIUM/HIGH/CRITICAL)'),
    sa.Column('sensitive_flag', sa.Boolean(), nullable=False, comment='敏感操作标记'),
    sa.Column('operation_result', sa.String(length=20), nullable=False, comment='操作结果(SUCCESS/FAILURE)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('before_data', sa.Text(), nullable=True, comment='操作前数据(JSON)'),
    sa.Column('after_data', sa.Text(), nullable=True, comment='操作后数据(JSON)'),
    sa.Column('business_context', sa.Text(), nullable=True, comment='业务上下文'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('resources',
    sa.Column('rid', sa.String(length=32), nullable=False),
    sa.Column('rname', sa.String(length=50), nullable=False),
    sa.Column('rcode', sa.String(length=50), nullable=False),
    sa.Column('rtype', sa.Enum('MENU', 'BUTTON', name='resourcetype'), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('menu_type', sa.Enum('GRID', 'LIST', 'CHART', 'DIR', name='menutype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rtype != 'BUTTON' OR parent_id IS NOT NULL", name='check_button_parent_required'),
    sa.CheckConstraint("rtype != 'MENU' OR menu_type IS NOT NULL", name='check_menu_menutype_required'),
    sa.ForeignKeyConstraint(['parent_id'], ['resources.rid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_resources_parent_id'), 'resources', ['parent_id'], unique=False)
    op.create_index(op.f('ix_resources_rcode'), 'resources', ['rcode'], unique=True)
    op.create_index(op.f('ix_resources_rid'), 'resources', ['rid'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=True)
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=True)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('role_area_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('area_id', sa.String(length=32), nullable=True),
    sa.Column('rid', sa.String(length=32), nullable=False),
    sa.Column('is_grant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['rid'], ['resources.rid'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'area_id', name='unique_role_area')
    )
    op.create_index(op.f('ix_role_area_grants_area_id'), 'role_area_grants', ['area_id'], unique=False)
    op.create_index(op.f('ix_role_area_grants_id'), 'role_area_grants', ['id'], unique=False)
    op.create_index(op.f('ix_role_area_grants_rid'), 'role_area_grants', ['rid'], unique=False)
    op.create_index(op.f('ix_role_area_grants_role_id'), 'role_area_grants', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'FROZEN', 'PENDING', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('idcard', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('default_role_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_users_idcard'), 'users', ['idcard'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('fileassets',
    sa.Column('fileid', sa.String(length=32), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'QUARANTINE', 'DELETED', 'MISSING', name='filestatus'), nullable=False),
    sa.Column('update_userid', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('fileid')
    )
    op.create_index(op.f('ix_fileassets_business_id'), 'fileassets', ['business_id'], unique=False)
    op.create_index(op.f('ix_fileassets_fileid'), 'fileassets', ['fileid'], unique=True)
    op.create_index(op.f('ix_fileassets_userid'), 'fileassets', ['userid'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('create_userid', sa.String(length=32), nullable=False),
    sa.Column('update_userid', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['create_userid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['update_userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_create_userid'), 'transactions', ['create_userid'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('user_role_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('area_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid', 'role_id', 'area_id', name='unique_user_role_area')
    )
    op.create_index(op.f('ix_user_role_scopes_area_id'), 'user_role_scopes', ['area_id'], unique=False)
    op.create_index(op.f('ix_user_role_scopes_id'), 'user_role_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_scopes_role_id'), 'user_role_scopes', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_scopes_userid'), 'user_role_scopes', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_scopes_userid'), table_name='user_role_scopes')
    op.drop_index(op.f('ix_user_role_scopes_role_id'), table_name='user_role_scopes')
    op.drop_index(op.f('ix_user_role_scopes_id'), table_name='user_role_scopes')
    op.drop_index(op.f('ix_user_role_scopes_area_id'), table_name='user_role_scopes')
    op.drop_table('user_role_scopes')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_create_userid'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_fileassets_userid'), table_name='fileassets')
    op.drop_index(op.f('ix_fileassets_fileid'), table_name='fileassets')
    op.drop_index(op.f('ix_fileassets_business_id'), table_name='fileassets')
    op.drop_table('fileassets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_idcard'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_area_grants_role_id'), table_name='role_area_grants')
    op.drop_index(op.f('ix_role_area_grants_rid'), table_name='role_area_grants')
    op.drop_index(op.f('ix_role_area_grants_id'), table_name='role_area_grants')
    op.drop_index(op.f('ix_role_area_grants_area_id'), table_name='role_area_grants')
    op.drop_table('role_area_grants')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resources_rid'), table_name='resources')
    op.drop_index(op.f('ix_resources_rcode'), table_name='resources')
    op.drop_index(op.f('ix_resources_parent_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_areas_parent_code'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_code'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
