"""update fileassets schema

Revision ID: 8eaa55769600
Revises: c842d3d8ef4c
Create Date: 2025-10-13 16:04:50.547850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaa55769600'
down_revision: Union[str, Sequence[str], None] = 'c842d3d8ef4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite 不支持直接添加 NOT NULL 列而不提供默认值
    # 因此我们采用三步法：添加可空列 -> 设置默认值 -> 修改为非空
    # 1. 添加可为空的列
    with op.batch_alter_table('fileassets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'QUARANTINE', 'DELETED', name='filestatus'), nullable=True))
    
    # 2. 为所有现有行设置默认值
    op.execute("UPDATE fileassets SET status = 'ACTIVE' WHERE status IS NULL")
    
    # 3. 将列修改为 NOT NULL
    with op.batch_alter_table('fileassets', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileassets', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
