"""再次完善表结构

Revision ID: a8c8bbf7fb04
Revises: 4f055d31e49f
Create Date: 2025-11-14 15:43:16.201125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c8bbf7fb04'
down_revision: Union[str, Sequence[str], None] = '4f055d31e49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role_scopes', 'status',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('user_role_scopes', 'is_default')
    op.add_column('users', sa.Column('default_role_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['default_role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_role_id')
    op.add_column('user_role_scopes', sa.Column('is_default', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('user_role_scopes', 'status',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    # ### end Alembic commands ###
