"""edit user summary view

Revision ID: c4bd1ef5f789
Revises: e05ca24ae97c
Create Date: 2025-11-05 15:39:30.938342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bd1ef5f789'
down_revision: Union[str, Sequence[str], None] = 'e05ca24ae97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE VIEW user_transaction_summary AS
    SELECT
        u.userid,  -- 用户ID
        u.username,  -- 用户名
        COUNT(t.transaction_id) AS total_transactions,  -- 总账单条数
        -- 收入总和（根据实际类型值调整条件）
        SUM(CASE WHEN t.type = 'INCOME' THEN t.amount ELSE 0 END) AS total_income,
        -- 支出总和（根据实际类型值调整条件）
        SUM(CASE WHEN t.type = 'EXPENSE' THEN t.amount ELSE 0 END) AS total_expense
    FROM users u
    LEFT JOIN transactions t ON t.create_userid = u.userid
    GROUP BY u.userid, u.username;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS user_transaction_summary;")
    # ### end Alembic commands ###
