"""重新整理表结构

Revision ID: c7c771d1290d
Revises: fa07b90aaa87
Create Date: 2025-11-13 15:03:20.971150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7c771d1290d'
down_revision: Union[str, Sequence[str], None] = 'fa07b90aaa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_index('ix_user_roles_userid', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_area_role_buttons_area_id', table_name='area_role_buttons')
    op.drop_index('ix_area_role_buttons_button_id', table_name='area_role_buttons')
    op.drop_index('ix_area_role_buttons_id', table_name='area_role_buttons')
    op.drop_index('ix_area_role_buttons_role_id', table_name='area_role_buttons')
    op.drop_table('area_role_buttons')
    op.drop_index('ix_role_buttons_button_id', table_name='role_buttons')
    op.drop_index('ix_role_buttons_id', table_name='role_buttons')
    op.drop_index('ix_role_buttons_role_id', table_name='role_buttons')
    op.drop_table('role_buttons')
    op.drop_index('ix_role_menus_id', table_name='role_menus')
    op.drop_index('ix_role_menus_menu_id', table_name='role_menus')
    op.drop_index('ix_role_menus_role_id', table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_index('ix_area_role_menus_area_id', table_name='area_role_menus')
    op.drop_index('ix_area_role_menus_id', table_name='area_role_menus')
    op.drop_index('ix_area_role_menus_menu_id', table_name='area_role_menus')
    op.drop_index('ix_area_role_menus_role_id', table_name='area_role_menus')
    op.drop_table('area_role_menus')
    op.drop_index('ix_buttons_button_code', table_name='buttons')
    op.drop_index('ix_buttons_button_id', table_name='buttons')
    op.drop_index('ix_buttons_menu_id', table_name='buttons')
    op.drop_table('buttons')
    op.drop_index('ix_menus_menu_code', table_name='menus')
    op.drop_index('ix_menus_menu_id', table_name='menus')
    op.drop_table('menus')
    op.drop_index('ix_users_area_id', table_name='users')
    op.drop_constraint('users_area_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'area_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_foreign_key('users_area_id_fkey', 'users', 'areas', ['area_id'], ['area_id'])
    op.create_index('ix_users_area_id', 'users', ['area_id'], unique=False)
    op.create_table('menus',
    sa.Column('menu_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menu_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('menu_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('GRID', 'LIST', 'CHART', name='menutype'), autoincrement=False, nullable=False),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('menu_id', name='menus_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_menus_menu_id', 'menus', ['menu_id'], unique=True)
    op.create_index('ix_menus_menu_code', 'menus', ['menu_code'], unique=True)
    op.create_table('buttons',
    sa.Column('button_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('button_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('button_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('menu_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], name='buttons_menu_id_fkey'),
    sa.PrimaryKeyConstraint('button_id', name='buttons_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_buttons_menu_id', 'buttons', ['menu_id'], unique=False)
    op.create_index('ix_buttons_button_id', 'buttons', ['button_id'], unique=True)
    op.create_index('ix_buttons_button_code', 'buttons', ['button_code'], unique=True)
    op.create_table('area_role_menus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('menu_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], name='area_role_menus_area_id_fkey'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], name='area_role_menus_menu_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='area_role_menus_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='area_role_menus_pkey'),
    sa.UniqueConstraint('role_id', 'area_id', 'menu_id', name='unique_area_role_menu', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_area_role_menus_role_id', 'area_role_menus', ['role_id'], unique=False)
    op.create_index('ix_area_role_menus_menu_id', 'area_role_menus', ['menu_id'], unique=False)
    op.create_index('ix_area_role_menus_id', 'area_role_menus', ['id'], unique=False)
    op.create_index('ix_area_role_menus_area_id', 'area_role_menus', ['area_id'], unique=False)
    op.create_table('role_menus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('menu_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], name='role_menus_menu_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='role_menus_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='role_menus_pkey'),
    sa.UniqueConstraint('role_id', 'menu_id', name='unique_role_menu', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_role_menus_role_id', 'role_menus', ['role_id'], unique=False)
    op.create_index('ix_role_menus_menu_id', 'role_menus', ['menu_id'], unique=False)
    op.create_index('ix_role_menus_id', 'role_menus', ['id'], unique=False)
    op.create_table('role_buttons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('button_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.button_id'], name='role_buttons_button_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='role_buttons_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='role_buttons_pkey'),
    sa.UniqueConstraint('role_id', 'button_id', name='unique_role_button', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_role_buttons_role_id', 'role_buttons', ['role_id'], unique=False)
    op.create_index('ix_role_buttons_id', 'role_buttons', ['id'], unique=False)
    op.create_index('ix_role_buttons_button_id', 'role_buttons', ['button_id'], unique=False)
    op.create_table('area_role_buttons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('button_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], name='area_role_buttons_area_id_fkey'),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.button_id'], name='area_role_buttons_button_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='area_role_buttons_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='area_role_buttons_pkey'),
    sa.UniqueConstraint('role_id', 'area_id', 'button_id', name='unique_area_role_button', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_area_role_buttons_role_id', 'area_role_buttons', ['role_id'], unique=False)
    op.create_index('ix_area_role_buttons_id', 'area_role_buttons', ['id'], unique=False)
    op.create_index('ix_area_role_buttons_button_id', 'area_role_buttons', ['button_id'], unique=False)
    op.create_index('ix_area_role_buttons_area_id', 'area_role_buttons', ['area_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='user_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], name='user_roles_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey'),
    sa.UniqueConstraint('userid', 'role_id', name='unique_user_role', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_user_roles_userid', 'user_roles', ['userid'], unique=False)
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_id', 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###
