"""update fileassets schema

Revision ID: c842d3d8ef4c
Revises: 6999cdf385c8
Create Date: 2025-09-30 16:12:33.249432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c842d3d8ef4c'
down_revision: Union[str, Sequence[str], None] = '6999cdf385c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileassets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fileid', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_fileassets_fileid'), ['fileid'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('INCOME', 'EXPENSE', name='transactiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', name='transactiontype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('fileassets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fileassets_fileid'))
        batch_op.drop_column('fileid')

    # ### end Alembic commands ###
