"""add_request_id_and_role_id_to_audit_logs

Revision ID: cd0d4bc672ea
Revises: 7909db436dc0
Create Date: 2025-11-19 13:53:56.932433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0d4bc672ea'
down_revision: Union[str, Sequence[str], None] = '7909db436dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('role_id', sa.String(length=32), nullable=True, comment='角色ID'))
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=32), nullable=True, comment='请求ID'))
    op.drop_index('idx_audit_level', table_name='audit_logs')
    op.drop_index('idx_audit_operation', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_operation', 'audit_logs', ['operation_type', 'operation_result'], unique=False)
    op.create_index('idx_audit_level', 'audit_logs', ['audit_level', 'created_at'], unique=False)
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'role_id')
    # ### end Alembic commands ###
