"""Initial migration after major schema changes

Revision ID: d95eace98ab8
Revises: 
Create Date: 2025-11-12 16:01:12.079858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95eace98ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('area_id', sa.String(length=32), nullable=False),
    sa.Column('area_code', sa.String(length=20), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_index(op.f('ix_areas_area_code'), 'areas', ['area_code'], unique=True)
    op.create_index(op.f('ix_areas_area_id'), 'areas', ['area_id'], unique=True)
    op.create_index(op.f('ix_areas_parent_code'), 'areas', ['parent_code'], unique=False)
    op.create_table('buttons',
    sa.Column('button_id', sa.String(length=32), nullable=False),
    sa.Column('button_name', sa.String(length=50), nullable=False),
    sa.Column('button_code', sa.String(length=50), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('button_id')
    )
    op.create_index(op.f('ix_buttons_button_code'), 'buttons', ['button_code'], unique=True)
    op.create_index(op.f('ix_buttons_button_id'), 'buttons', ['button_id'], unique=True)
    op.create_table('menus',
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('menu_name', sa.String(length=50), nullable=False),
    sa.Column('menu_code', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('GRID', 'LIST', 'CHART', name='menutype'), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menus_menu_code'), 'menus', ['menu_code'], unique=True)
    op.create_index(op.f('ix_menus_menu_id'), 'menus', ['menu_id'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=True)
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=True)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('area_role_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('area_id', sa.String(length=32), nullable=False),
    sa.Column('button_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.button_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'area_id', 'button_id', name='unique_area_role_button')
    )
    op.create_index(op.f('ix_area_role_buttons_area_id'), 'area_role_buttons', ['area_id'], unique=False)
    op.create_index(op.f('ix_area_role_buttons_button_id'), 'area_role_buttons', ['button_id'], unique=False)
    op.create_index(op.f('ix_area_role_buttons_id'), 'area_role_buttons', ['id'], unique=False)
    op.create_index(op.f('ix_area_role_buttons_role_id'), 'area_role_buttons', ['role_id'], unique=False)
    op.create_table('area_role_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('area_id', sa.String(length=32), nullable=False),
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'area_id', 'menu_id', name='unique_area_role_menu')
    )
    op.create_index(op.f('ix_area_role_menus_area_id'), 'area_role_menus', ['area_id'], unique=False)
    op.create_index(op.f('ix_area_role_menus_id'), 'area_role_menus', ['id'], unique=False)
    op.create_index(op.f('ix_area_role_menus_menu_id'), 'area_role_menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_area_role_menus_role_id'), 'area_role_menus', ['role_id'], unique=False)
    op.create_table('role_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('button_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.button_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'button_id', name='unique_role_button')
    )
    op.create_index(op.f('ix_role_buttons_button_id'), 'role_buttons', ['button_id'], unique=False)
    op.create_index(op.f('ix_role_buttons_id'), 'role_buttons', ['id'], unique=False)
    op.create_index(op.f('ix_role_buttons_role_id'), 'role_buttons', ['role_id'], unique=False)
    op.create_table('role_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id', name='unique_role_menu')
    )
    op.create_index(op.f('ix_role_menus_id'), 'role_menus', ['id'], unique=False)
    op.create_index(op.f('ix_role_menus_menu_id'), 'role_menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_role_menus_role_id'), 'role_menus', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid', 'role_id', name='unique_user_role')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_userid'), 'user_roles', ['userid'], unique=False)
    op.create_foreign_key(None, 'fileassets', 'users', ['userid'], ['userid'])
    op.create_foreign_key(None, 'loggers', 'users', ['userid'], ['userid'])
    op.execute("DROP VIEW IF EXISTS user_transaction_summary CASCADE;")
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint('transactions_pk', 'transactions', type_='unique')
    op.create_foreign_key(None, 'transactions', 'users', ['create_userid'], ['userid'])
    op.create_foreign_key(None, 'transactions', 'users', ['update_userid'], ['userid'])
    op.drop_constraint('users_pk', 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['area_id'])

    op.execute("""
    CREATE OR REPLACE VIEW user_transaction_summary AS
    SELECT
        u.userid,  -- 用户ID
        u.username,  -- 用户名
        COUNT(t.transaction_id) AS total_transactions,  -- 总账单条数
        -- 收入总和（根据实际类型值调整条件）
        SUM(CASE WHEN t.type = 'INCOME' THEN t.amount ELSE 0 END) AS total_income,
        -- 支出总和（根据实际类型值调整条件）
        SUM(CASE WHEN t.type = 'EXPENSE' THEN t.amount ELSE 0 END) AS total_expense
    FROM users u
    LEFT JOIN transactions t ON t.create_userid = u.userid
    GROUP BY u.userid, u.username;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS user_transaction_summary CASCADE;")
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint('users_pk', 'users', ['userid'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_unique_constraint('transactions_pk', 'transactions', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'loggers', type_='foreignkey')
    op.drop_constraint(None, 'fileassets', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_userid'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_menus_role_id'), table_name='role_menus')
    op.drop_index(op.f('ix_role_menus_menu_id'), table_name='role_menus')
    op.drop_index(op.f('ix_role_menus_id'), table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_index(op.f('ix_role_buttons_role_id'), table_name='role_buttons')
    op.drop_index(op.f('ix_role_buttons_id'), table_name='role_buttons')
    op.drop_index(op.f('ix_role_buttons_button_id'), table_name='role_buttons')
    op.drop_table('role_buttons')
    op.drop_index(op.f('ix_area_role_menus_role_id'), table_name='area_role_menus')
    op.drop_index(op.f('ix_area_role_menus_menu_id'), table_name='area_role_menus')
    op.drop_index(op.f('ix_area_role_menus_id'), table_name='area_role_menus')
    op.drop_index(op.f('ix_area_role_menus_area_id'), table_name='area_role_menus')
    op.drop_table('area_role_menus')
    op.drop_index(op.f('ix_area_role_buttons_role_id'), table_name='area_role_buttons')
    op.drop_index(op.f('ix_area_role_buttons_id'), table_name='area_role_buttons')
    op.drop_index(op.f('ix_area_role_buttons_button_id'), table_name='area_role_buttons')
    op.drop_index(op.f('ix_area_role_buttons_area_id'), table_name='area_role_buttons')
    op.drop_table('area_role_buttons')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_menus_menu_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_menu_code'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_buttons_button_id'), table_name='buttons')
    op.drop_index(op.f('ix_buttons_button_code'), table_name='buttons')
    op.drop_table('buttons')
    op.drop_index(op.f('ix_areas_parent_code'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_code'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
