"""create user summary view

Revision ID: e05ca24ae97c
Revises: 4a9c5e5b47c2
Create Date: 2025-10-30 09:13:17.756148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05ca24ae97c'
down_revision: Union[str, Sequence[str], None] = '4a9c5e5b47c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE VIEW v_user_txn_summary AS
    SELECT
        u.userid,
        u.username,
        COUNT(t.transaction_id)::bigint AS txn_count,
        COALESCE(SUM(t.amount), 0)::numeric(18,2) AS total_amount
    FROM users u
    LEFT JOIN transactions t ON t.create_userid = u.userid
    GROUP BY u.userid, u.username;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_user_txn_summary;")
    # ### end Alembic commands ###
