"""add_device_fingerprint_to_audit_logs

Revision ID: e77169ba4a78
Revises: 58733a662944
Create Date: 2025-11-19 14:01:46.296681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77169ba4a78'
down_revision: Union[str, Sequence[str], None] = '58733a662944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('device_fingerprint', sa.String(length=255), nullable=True, comment='设备指纹'))
    op.add_column('audit_logs', sa.Column('browser_type', sa.String(length=50), nullable=True, comment='浏览器类型'))
    op.add_column('audit_logs', sa.Column('os_type', sa.String(length=50), nullable=True, comment='操作系统类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'os_type')
    op.drop_column('audit_logs', 'browser_type')
    op.drop_column('audit_logs', 'device_fingerprint')
    # ### end Alembic commands ###
