"""add_response_status_and_response_time_to_audit_logs

Revision ID: ebcee47f145b
Revises: cd0d4bc672ea
Create Date: 2025-11-19 13:56:26.911985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcee47f145b'
down_revision: Union[str, Sequence[str], None] = 'cd0d4bc672ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP响应状态码'))
    op.add_column('audit_logs', sa.Column('response_time', sa.Float(), nullable=True, comment='响应时间(秒)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'response_time')
    op.drop_column('audit_logs', 'response_status')
    # ### end Alembic commands ###
