"""完善资源表约束

Revision ID: f9bdfc011b5d
Revises: a437fa5a7013
Create Date: 2025-11-13 15:37:02.347785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bdfc011b5d'
down_revision: Union[str, Sequence[str], None] = 'a437fa5a7013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'menu_type', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'menu_type', nullable=True)
    # ### end Alembic commands ###
