"""按钮表增加menu_id

Revision ID: fa07b90aaa87
Revises: d95eace98ab8
Create Date: 2025-11-12 17:15:57.105221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa07b90aaa87'
down_revision: Union[str, Sequence[str], None] = 'd95eace98ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('menu_id', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_buttons_menu_id'), 'buttons', ['menu_id'], unique=False)
    op.create_foreign_key(None, 'buttons', 'menus', ['menu_id'], ['menu_id'])
    op.alter_column('users', 'area_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'area_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'buttons', type_='foreignkey')
    op.drop_index(op.f('ix_buttons_menu_id'), table_name='buttons')
    op.drop_column('buttons', 'menu_id')
    # ### end Alembic commands ###
